IMS_V1/Models/ItemAttribute.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IMS_V1.Models
{
    public class ItemAttributeModel
    {
        public int ItemAttribute_Id { get; set; }
        public Nullable<int> Item_Id { get; set; }
        public Nullable<int> AttributeLookup_Id { get; set; }
        public string ActualAttributeValue { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }

        public Attribute_Lookup Attribute_Lookup { get; set; }
        public AttributeType AttributeType { get; set; }
        public CategoryAttribute CategoryAttributes { get; set; }
        public Item Item { get; set; }
    }
}

IMS_V1/Controllers/ItemAttributeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity.Validation;
namespace IMS_V1.Controllers
{
    public class ItemAttributeController : Controller
    {
        private IMS_V1Entities db = new IMS_V1Entities();

        //
        // GET: /ItemAttribute/

        public ActionResult Index(int id)
        {
            Session["ItemID"] = id;
            var itemattribute = db.ItemAttributes.Include(i => i.Attribute_Lookup.AttributeType).Include(i => i.Item).Where(i => i.Item_Id == id);
            ViewBag.Itm_num = db.Items.Where(i => i.Item_id == id).Select(i => i.Itm_Num).Single();
            ViewBag.ItemDescription = db.Items.Where(i => i.Item_id == id).Select(i => i.Item_Description).Single();
            ViewBag.SFItemDescription = db.Items.Where(i => i.Item_id == id).Select(i => i.SF_Item_Description).Single();
            ViewBag.Printed = db.Items.Where(i => i.Item_id == id).Select(i => i.Printed).Single();
            ViewBag.Item_Id = id;
            ViewBag.ReadyForApproval = db.Items.Where(i => i.Item_id == id).Select(i => i.ReadyForApproval).Single();
            ViewBag.FastTrack = db.Items.Where(i => i.Item_id == id).Select(i => i.FastTrack).Single();
            ViewBag.Company99 = db.Items.Where(i => i.Item_id == id).Select(i => i.Company99).Single();
            ViewBag.Company99_List = new SelectList(
                                new List<SelectListItem>
                                {
                                    //new SelectListItem { Text = "", Value = "",Selected = (ViewBag.Company99 == "")},
                                    new SelectListItem { Text = "99", Value = "99",Selected = (ViewBag.Company99 == "99")},
                                }, "Value", "Text");
            if (Session["itemDescriptionError"] != null)
            {
                string itemDescriptionError = Session["itemDescriptionError"].ToString();
                if (itemDescriptionError.Trim().Length > 0)
                    ViewBag.ItemDescriptionError = Session["itemDescriptionError"];
            }
            Session["itemDescriptionError"] = null;
            if (Session["CreateError"] != null)
            {
                string itemDescriptionError = Session["CreateError"].ToString();
                if (itemDescriptionError.Trim().Length > 0)
                    ViewBag.ItemDescriptionError = itemDescriptionError;
            }
            Session["CreateError"] = null; 
            GetRemainingAttributeTypes(id);
            GetRemainingAttributeTypesCount(id);
            GetCategoryClass(id);
            //if (ViewBag.ItemDescription != null)
            //{
            //    int idl = ViewBag.ItemDescription.Length;
            //    if (idl > 31)
            //    {
            //        ViewBag.AplusDesc1 = ViewBag.ItemDescription.Substring(0, 31);
            //        ViewBag.APlusDesc2 = ViewBag.ItemDescription.Substring(31, idl - 31);
            //    }
            //    else
            //    {
            //        ViewBag.AplusDesc1 = ViewBag.ItemDescription;
            //        ViewBag.APlusDesc2 = "";
            //    }
            //}
            ViewBag.AplusDesc1 = db.Items.Where(i => i.Item_id == id).Select(i => i.APlusDescription1).Single();
            ViewBag.AplusDesc2 = db.Items.Where(i => i.Item_id == id).Select(i => i.APlusDescription2).Single();
            return View(itemattribute.ToList());
        }

        [HttpPost]
        public ActionResult SaveDescription(int id)
        {
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            string nd = Request.Form["txtItemDescription"];
            var vinfo = (from v in db.zManufacturersLogoes
                         where v.ManufacturerLogo_Id == item.ManufacturerLogo_Id && v.Enabled == true
                         select new { v.APlusVendorName, v.Abbrev, v.VendorNumber, v.ManufacturerLogo_Id, v.WebVendorName }).SingleOrDefault();
            if (nd != null)
            {
                int index = nd.IndexOf(" ");
                string vendorAbbrev;
                if (index < 0)
                    vendorAbbrev = nd.Trim();
                else
                    vendorAbbrev = nd.Substring(0, index);
                if (!vendorAbbrev.Equals(vinfo.Abbrev.Trim()))
                    ModelState.AddModelError("Item_Description", "The first word of Item Description must be the vendor abbrevation!");
            }
            if (ModelState.IsValid)
            {
                if (nd != null)
                {
                    var result1 = db.Database.ExecuteSqlCommand("UpdateItemDescription @Item_Id,@NewDescription,@UserId", new SqlParameter("@Item_Id", id),
                                                                                                new SqlParameter("@NewDescription", nd),
                                                                                                new SqlParameter("@UserId", int.Parse(Session.Contents["UserId"].ToString())));
                }

                //string sfnd = Request.Form["txtSFItemDescription"];
                //if (sfnd != null)
                //{
                //    var resultSFItemDescription = db.Database.ExecuteSqlCommand("UpdateSFItemDescription @Item_Id,@NewSFDescription,@UserId", new SqlParameter("@Item_Id", id),
                //                                                                                new SqlParameter("@NewSFDescription", sfnd),
                //                                                                                new SqlParameter("@UserId", int.Parse(Session.Contents["UserId"].ToString())));
                //}
                var company99 = Request.Form["Company99"];
                string c99 = "";
                if (company99 != null)
                {
                    c99 = company99;
                }

                string srfa = "";
                string sft = "";
                var rfa = Request.Form["chkReadyForApproval"];
                //string chkspecialorder;
                if (rfa == "on")
                {
                    srfa = "Y";
                }
                else
                {
                    srfa = "N";
                }

                var ft = Request.Form["chkFastTrack"];
                //string chkspecialorder;
                if (ft == "on")
                {
                    sft = "Y";
                }
                else
                {
                    sft = "N";
                }


                var result2 = db.Database.ExecuteSqlCommand("UpdateItemRFA_FT @Item_Id,@ReadyForApproval,@FastTrack,@UserId,@Company99", new SqlParameter("@Item_Id", id),
                                                                                            new SqlParameter("@ReadyForApproval", srfa),
                                                                                            new SqlParameter("@FastTrack", sft),
                                                                                            new SqlParameter("@UserId", int.Parse(Session.Contents["UserId"].ToString())),
                                                                                            new SqlParameter("@Company99", c99));

                string checkErr = CheckAttributesCompletion(id);
                if (checkErr == "")
                    return RedirectToAction("Index", "ReplacementItem", new { id = id });
                else
                {
                    checkErr = checkErr.Substring(0, checkErr.Length - 1);
                    checkErr = checkErr + " required.";
                    Session["itemDescriptionError"] = checkErr;
                    return RedirectToAction("Index", new { id = id });
                }
                
            }
            else
            {
                Session["itemDescriptionError"] = "The first word of Item Description must be the vendor abbrevation!";
                return RedirectToAction("Index", new { id = id });
            }
        }

        public string CheckAttributesCompletion(int Itemid)
        {
            string retMessages = "";
            Item item = db.Items.Find(Itemid);

            var results1 = db.GetRemainingAttributeTypes(Itemid);
            List<GetRemainingAttributeTypes_Result> remainingTypes = results1.ToList();
            if (item == null)
                retMessages = "Item not found";
            else
            {
                foreach (var r in remainingTypes)
                {
                    if (r.REQUIRED.Value)
                        retMessages += " " + r.attributeType + ",";
                    else if (item.CategoryClass.CategoryClass_Id == 1 && r.attributeType.Equals("Finish"))
                        retMessages += " " + r.attributeType + ",";
                    //else if (item.CategoryClass.CategoryClass_Id == 2 && r.attributeType.Equals("Misc 1")) remove it by Myke's request
                    //    retMessages += " " + r.attributeType + ",";
                    else if (item.CategoryClass.CategoryClass_Id == 3 && r.attributeType.Equals("Feet Per Second"))
                        retMessages += " " + r.attributeType + ",";
                }
            }
            return retMessages.Trim();
        }

        [HttpPost]
        public ActionResult SaveRFA_FastTrack(int id)
        {

            string srfa = "";
            string sft = "";
            var rfa = Request.Form["chkReadyForApproval"];
            //string chkspecialorder;
            if (rfa == "on")
            {
                srfa = "Y";
            }
            else
            {

IMS_V1/Controllers/ItemTextAttachmentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IMS_V1.Controllers
{
    public class ItemTextAttachmentController : Controller
    {
        private IMS_V1Entities db = new IMS_V1Entities();

        //
        // GET: /ItemTextAttachment/

        public ActionResult Index(int itemid)
        {
            //var itemtextattachments = db.ItemTextAttachments.Include(i => i.Item).Select(i=>i.Text).ToString();
            GetExistingLongDescriptions(itemid);

            ViewBag.Itm_num = db.Items.Where(i => i.Item_id == itemid).Select(i => i.Itm_Num).Single();

           ViewBag.ItemDescription = db.Items.Where(i => i.Item_id == itemid).Select(i => i.Item_Description).Single();
            //ViewBag.ItemDescription = db.Items.Where(i => i.Item_id == id).Select(i => i.Item_Description).Single();
            //byte[] binaryString = (byte[])db.Items.Where(i => i.Item_id == id).Select(i => i.Item_Description).Single();

            // if the original encoding was ASCII
            //string x = Encoding.ASCII.GetString(binaryString);
            ViewBag.Item_Id = itemid;
            return View();
        
        }

        //
        // GET: /ItemTextAttachment/Create

        public ActionResult Create(int itemid,string itmnum,string itemdescription)
        {
            ViewBag.Item_id = itemid;
            ViewBag.Itm_Num = itmnum;
            ViewBag.Item_Description = itemdescription;
            return View();
        }

        //
        // POST: /ItemTextAttachment/Create

        [HttpPost]
        public ActionResult Create(ItemTextAttachment itemtextattachment)
        {
            string txa = Request.Form["txaLongDescription"];
            int itemid = Convert.ToInt32(Request.Form["hdnItem_id"]);
            int userid = int.Parse(Session.Contents["UserId"].ToString());
            try
            {
                AddLongDescription(itemid, txa,userid);
                return RedirectToAction("Index", new { itemid = itemid });
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Unable to save changes.  Try, again later please.");
            }
           
            return View();

        }

        //
        // GET: /ItemTextAttachment/Edit/5

        public ActionResult Edit(int id = 0)
        {
            GetEditLongDescription(id);
            foreach (var ld in ViewBag.EditLongDescription)
            {
                ViewBag.ItemTextAttachment_Id = ld.ItemTextAttachment_Id;
                ViewBag.Item_id = ld.item_id;
                ViewBag.Itm_Num = ld.itm_num;
                ViewBag.Item_Description = ld.Item_Description;
                ViewBag.LongDescription = ld.LongDescription;
            }
            return View();
        }

        //
        // POST: /ItemTextAttachment/Edit/5

        [HttpPost]
        public ActionResult Edit(ItemTextAttachment itemtextattachment)
        {
            int id = Convert.ToInt32(Request.Form["hdnItemTextAttachment_Id"]);
            string txa = Request.Form["txaLongDescription"];
            string itemid = Request.Form["hdnItem_id"];

            try
            {
                UpdateLongDescription(id, txa);
                return RedirectToAction("Index", new { itemid = itemid });
            } catch (DataException)
            {
                ModelState.AddModelError("", "Unable to save changes.  Try, again later please." );
            }
    
            GetEditLongDescription(id);
            foreach (var ld in ViewBag.EditLongDescription)
            {
                ViewBag.Item_id = ld.item_id;
                ViewBag.Itm_Num = ld.itm_num;
                ViewBag.Item_Description = ld.Item_Description;
                ViewBag.LongDescription = ld.LongDescription;
            }
            return View();
        }

        //
        // GET: /ItemTextAttachment/Delete/5

        public ActionResult Delete(int id = 0)
        {
            GetEditLongDescription(id);
            foreach (var ld in ViewBag.EditLongDescription)
            {
                ViewBag.ItemTextAttachment_Id = ld.ItemTextAttachment_Id;
                ViewBag.Item_id = ld.item_id;
                ViewBag.Itm_Num = ld.itm_num;
                ViewBag.Item_Description = ld.Item_Description;
                ViewBag.LongDescription = ld.LongDescription;
            }
            return View();
            
        }

        //
        // POST: /ItemTextAttachment/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            ItemTextAttachment itemtextattachment = db.ItemTextAttachments.Find(id);
            db.ItemTextAttachments.Remove(itemtextattachment);
            db.SaveChanges();
            string txa = Request.Form["txaLongDescription"];
            string itemid = Request.Form["hdnItem_id"];

            return RedirectToAction("Index", new { itemid = itemid });

        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        public void GetExistingLongDescriptions(int Itemid)
        {

            var results2 = db.GetExistingLongDescriptions(Itemid);
            ViewBag.LongDescriptions = results2.ToList();
        }

        public void GetEditLongDescription(int id)
        {

            var results3 = db.GetLongDescription(id);
            ViewBag.EditLongDescription = results3.ToList();

        }

        public void UpdateLongDescription(int id,string LongDescription)
        {

            var results3 = db.UpdateLongDescription(id,LongDescription);

        }

        public void AddLongDescription(int id,string LongDescription,int userid)
        {

            var results3 = db.AddLongDescription(id,LongDescription,userid);

        }

    }
}

IMS_V1/Views/ItemAttribute/Create.cshtml
@model IMS_V1.ItemAttribute

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
 <script type="text/javascript">
     $(document).unbind('keydown').bind('keydown', function (event) {
         var doPrevent = false;
         if (event.keyCode === 8) {
             var d = event.srcElement || event.target;
             if ((d.tagName.toUpperCase() === 'INPUT' &&
                  (
                      d.type.toUpperCase() === 'TEXT' ||
                      d.type.toUpperCase() === 'PASSWORD' ||
                      d.type.toUpperCase() === 'FILE' ||
                      d.type.toUpperCase() === 'SEARCH' ||
                      d.type.toUpperCase() === 'EMAIL' ||
                      d.type.toUpperCase() === 'NUMBER' ||
                      d.type.toUpperCase() === 'DATE')
                  ) ||
                  d.tagName.toUpperCase() === 'TEXTAREA') {
                 doPrevent = d.readOnly || d.disabled;
             }
             else {
                 doPrevent = true;
             }
         }
         if (doPrevent) {
             event.preventDefault();
         }
     });
     $(document).ready(function () {
         $("#ddlAttributeType").change(function () {
             var AttributeTypeId = $(this).val();
             $.getJSON("../ItemAttribute/LoadAttributeLookup", { attributetypeid: AttributeTypeId },
             function (AttributeLookupData) {
                 var select = $("#ddlAttributeLookup");
                 select.empty();
                 select.append($('<option/>', {
                     value: 0,
                     text: "Select a Attribute Value"
                 }));
                 $.each(AttributeLookupData, function (index, itemData) {
                     select.append($('<option/>', {
                         value: itemData.Value,
                         text: itemData.Text
                     }));
                 });
             });
         });
         var changeAttribute = $("#ddlAttributeLookup").change(function () {
             var AttributeLookup_Id = $(this).val();
             $.getJSON("../ItemAttribute/LoadAttributeInfo", { Aid: AttributeLookup_Id },
                    function (AttributeData) {
                        $("#APlusValue").val(AttributeData.APlusAttributeValue);
                        $("#DefaultValue").val(AttributeData.DefaultActualValue);
                    }).fail(function (xhr, textStatus, errorThrown) { alert(xhr.responseText); });
         });
     });
</script>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <table>
        <tr>
            <td colspan="2" style="text-align:left">
                @Html.HiddenFor(model => model.ItemAttribute_Id)
                @Html.HiddenFor(model => model.Item_Id)

                <b>Item Number:</b> @ViewBag.Itm_num
                <br />
                <b>Item Description:</b> @ViewBag.ItemDescription
            </td>
        </tr>

        <tr>
            <td>
                Attribute Type:
            </td>
            <td>
                @Html.DropDownList("AttributeType_Id", (IEnumerable<SelectListItem>)ViewBag.AttributeType, "- - - S E L E C T - - -", new { id = "ddlAttributeType", style = "width:350px;" })  
            </td>
        </tr>
        <tr>
            <td>
                Website Attribute Value:
            </td>
            <td style="text-align:left" class="textbox">
                @Html.DropDownList("AttributeLookup_Id", (IEnumerable<SelectListItem>)ViewBag.AttributeLookup, "- - - S E L E C T - - -", new { id = "ddlAttributeLookup", style = "width:350px;" })  
            </td>
        </tr>
<!--        <tr>
            <td>
                APlus Attribute Value:
            </td>
            <td style="text-align:left" class="textbox">
               @*Html.TextBox("APlusValue","",  new { @readonly = "readonly", style = "width:120px;"})*@
            </td>
        </tr>
        <tr>
            <td>
                Default Attribute Value:
            </td>
            <td style="text-align:left" class="textbox">
               @*Html.TextBox("DefaultValue","",  new { @readonly = "readonly", style = "width:120px;"})*@
            </td>
        </tr>-->

        <tr>
            <td>
                Actual Attribute Value:
            </td>
            <td style="text-align:left" class="textbox">
                @Html.EditorFor(model => model.ActualAttributeValue)
                @Html.ValidationMessageFor(model => model.ActualAttributeValue)
            </td>
        </tr>
        <tr>
            <td style="text-align:center" colspan="2">
        @if (int.Parse(Session.Contents["UserTypeID"].ToString()) != 6){
                <input type="submit" value="Save" />
        }else{
            if(ViewBag.Printed != "Y"){
                <input type="submit" value="Save" />
            }
        }
            </td>
        </tr>
    </table>

}

<div>
    @Html.ActionLink("Back to List", "Index", new{ id = ViewBag.Item_Id })

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IMS_V1/Views/ItemAttribute/Index.cshtml
@model IEnumerable<IMS_V1.ItemAttribute>

@{
    ViewBag.Title = "Attribute List";
}

<table style="width:1000px">
    <tr>
        <td colspan="3" style="text-align:center">
            <h2>Attribute List</h2>
        </td>
        <!--<td></td>-->
    </tr>
@using (Html.BeginForm("SaveDescription", "ItemAttribute", new { id = ViewBag.Item_Id }, FormMethod.Post))
{
    <tr>
        <td colspan="3" style="text-align:left">
            <b>Item Number:</b> @ViewBag.Itm_num
            <br />
      @Html.ValidationSummary(true)
    @if (ViewBag.CategoryClass=="N")
    {
       <b>Item Description:</b> <input type="text" style="width:450px;" name="txtItemDescription" id="txtItemDescription" value="@ViewBag.ItemDescription"/>
        if (ViewBag.ItemDescriptionError != null && ViewBag.ItemDescriptionError.Trim().Length > 0)
        { 
            <br /><span style="color:red;">@ViewBag.ItemDescriptionError</span>
        }
<!--        if (int.Parse(Session.Contents["UserTypeID"].ToString()) != 6){
            <input type="submit" value="Save" /> <br />
        }else{
            if(ViewBag.Printed != "Y"){
            <input type="submit" value="Save" /> <br />
            }
        }-->
        <br />
        
        <Desc1>@ViewBag.APlusDesc1</Desc1> <Desc2>@ViewBag.APlusDesc2</Desc2>
        <br />
        <br /> <b>Storefront Item Description:</b> 
            <textarea style="width:1000px; height:75px; " readonly name="txtSFItemDescription" id="txtSFItemDescription" >
                @ViewBag.SFItemDescription
            </textarea>   
            
    }else
    {
             <b>Item Description:</b>  @ViewBag.ItemDescription<br />
        if (ViewBag.ItemDescriptionError != null && ViewBag.ItemDescriptionError.Trim().Length > 0)
        { 
            <span style="color:red;">@ViewBag.ItemDescriptionError</span><br />
        }
        <Desc1>@ViewBag.APlusDesc1</Desc1> <Desc2>@ViewBag.APlusDesc2</Desc2>
        <br />
        <br /> <b>Storefront Item Description:</b> @ViewBag.SFItemDescription
    }
<!--}-->
        </td>
    </tr>
               if (ViewBag.RemainingAttributeTypes.Count != 0)
               {
<!--    <tr>
        <td colspan="2" style="text-align:right">
                <b>Bold</b> items are required.
        </td>
        <td></td>
    </tr>-->
    
    <tr>
        <td colspan="2" style ="vertical-align:central; text-align:right">
            <br />
            <br />
            <br />
            The Remaining Attributes must be added before Item can be approved for setup:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<!--        </td>
        <td style="text-align:left">-->
                   @foreach (var rat in ViewBag.RemainingAttributeTypes)
                    {

                       if (rat.REQUIRED)                           
                       {
                          <b> @rat.attributeType </b><br /> 
                       }else
                       {
                            @rat.attributeType <br /> 
                       }
            
                    }
        </td>
        <td style="text-align:left; vertical-align:top">
            <br />
            <br />
            <br />
            &nbsp;&nbsp;&nbsp;&nbsp;(<b>Bold</b> items are required.)
        </td>
    </tr>
               }
<!--using (Html.BeginForm("SaveRFA_FastTrack", "ItemAttribute", new { id = ViewBag.Item_Id }, FormMethod.Post))
{-->
      <!--Html.ValidationSummary(true)-->

     <tr>
    
  
         
        <!--if (int.Parse(Session.Contents["UserTypeID"].ToString()) != 6){
            <input type="submit" value="Save" /> <br />
        }else{
            if(ViewBag.Printed != "Y"){
            <input type="submit" value="Save" /> <br />
            }
        }-->         
         
           
            @if (ViewBag.AllRequired == 0 && (int.Parse(Session.Contents["UserTypeID"].ToString()) != 6))
            {
            <td class="textbox"  style="text-align:center">
                Ready For Approval:
                <input type="checkbox" name="chkReadyForApproval" id="chkReadyForApproval" @(ViewBag.ReadyForApproval == "Y" ? "checked='checked'" : "") />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </td>
            }

            @if (int.Parse(Session.Contents["UserTypeID"].ToString()) != 6){
            <td class="textbox" style="text-align:center">
                Fast Track:
                <input type="checkbox" name="chkFastTrack" id="chkFastTrack" @(ViewBag.FastTrack == "Y" ? "checked='checked'" : "") />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </td>
            }
             <td></td>
    </tr>
        <tr>
            <td>
                Company:
            </td>
            <td class="textbox" colspan="2">
                @Html.DropDownList("Company99", (IEnumerable<SelectListItem>)ViewBag.Company99_List, "- - - S E L E C T - - -")  
                <span style="color:red;">Select 99 to HIDE ITEM in APLUS.</span>
            </td>
        </tr>

         <tr>          
             <td colspan ="3" style="text-align:center;">
                @if(ViewBag.Printed != "Y"){
                    <input type="submit" value="Save" />
                }
            </td>
        </tr>
    
    
    
    
    
<!--        if (ViewBag.AllRequired == 0)
            {
            <td class="textbox" style="text-align:center">
                Ready For Approval:
                <input type="checkbox" name="chkReadyForApproval" id="chkReadyForApproval" (ViewBag.ReadyForApproval == "Y" ? "checked='checked'" : "") />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </td>
            }

            <td class="textbox" style="text-align:center">
                Fast Track:
                <input type="checkbox" name="chkFastTrack" id="chkFastTrack" (ViewBag.FastTrack == "Y" ? "checked='checked'" : "") />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <input type="submit" value="Save" />
            </td>-->

}

</table>


<p>
        @Html.ActionLink("Add New Attribute", "Create", new { item_id = ViewBag.Item_Id })


</p>

<table style="width:1000px">
    <tr>
        <td colspan="5">
     @if (int.Parse(Session.Contents["UserTypeID"].ToString()) != 6){
            @Html.ActionLink("Back to Item","Edit","Item",new {id=ViewBag.Item_Id},null)
    }else{
            @Html.ActionLink("Back to Item","VendorEdit","Item",new {id=ViewBag.Item_Id},null)
    }
    @if (int.Parse(Session.Contents["UserTypeID"].ToString()) == 7 || int.Parse(Session.Contents["UserTypeID"].ToString()) == 8 || int.Parse(Session.Contents["UserTypeID"].ToString()) == 1)
    {
        @Html.ActionLink("Text Attachment","Index","ItemTextAttachment",new {itemid=ViewBag.Item_Id},null)
    }

        </td>
    </tr>
    <tr>
        <th>
            Attribute Type
        </th>
        <th>
            Aplus Value
        </th>
        <th>
            Website Value
        </th>
        <th>
            ActualAttributeValue
        </th>
        <th>
        <th></th>
    </tr>
@{var bkc = "whitesmoke";}
@foreach (var item in Model) {
    if (bkc == "whitesmoke")
    {
        bkc = "white";
    }
    else
    {
        bkc = "whitesmoke";
    }       
    <tr style="background-color:@bkc;">
        <td class="display1">
            @Html.ActionLink(item.Attribute_Lookup.AttributeType.AttributeType1.ToString(), "Edit", new {attributeName = item.Attribute_Lookup.AttributeType.AttributeType1 ,  id = item.ItemAttribute_Id })
        </td>
        <td class="display1">
            @Html.DisplayFor(modelItem => item.Attribute_Lookup.APlusAttributeValue)
        </td>
        <td class="display1">
            @Html.DisplayFor(modelItem => item.Attribute_Lookup.WebsiteAttributeValue)
        </td>
        <td class="display1">
            @Html.DisplayFor(modelItem => item.ActualAttributeValue)
        </td>
        <td style="font-size:.70em">
            @Html.ActionLink("Edit", "Edit", new {attributeName = item.Attribute_Lookup.AttributeType.AttributeType1 ,  id = item.ItemAttribute_Id }) |
            @Html.ActionLink("Delete", "Delete", new {attributeName = item.Attribute_Lookup.AttributeType.AttributeType1 , id = item.ItemAttribute_Id })
        </td>
    </tr>
}
    <tr>
        <td colspan="100" style="text-align:center">
             @Html.ActionLink("Back to List", "Index","Item")
        </td>
    </tr>
   

</table>