IMS_V1/Controllers/AttributeTypeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IMS_V1.Controllers
{
    public class AttributeTypeController : Controller
    {
        private IMS_V1Entities db = new IMS_V1Entities();

        //
        // GET: /AttributeType/

        public ActionResult Index()
        {
            var attributes = from at in db.AttributeTypes
                        orderby at.AttributeType1
                        select at;

            return View(attributes.ToList());
        }

        //
        // GET: /AttributeType/Details/5

        public ActionResult Details(int id = 0)
        {
            AttributeType attributetype = db.AttributeTypes.Find(id);
            if (attributetype == null)
            {
                return HttpNotFound();
            }
            return View(attributetype);
        }

        //
        // GET: /AttributeType/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /AttributeType/Create

        [HttpPost]
        public ActionResult Create([Bind(Exclude = "AttributeType_Id")]AttributeType attributetype)
        {
            if (ModelState.IsValid)
            {
                db.AttributeTypes.Add(attributetype);
                int userid = int.Parse(Session.Contents["UserID"].ToString());
                attributetype.ModifiedBy = userid;
                attributetype.ModifiedDate = DateTime.Now;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(attributetype);
        }

        //
        // GET: /AttributeType/Edit/5

        public ActionResult Edit(int id = 0)
        {
            AttributeType attributetype = db.AttributeTypes.Find(id);
            if (attributetype == null)
            {
                return HttpNotFound();
            }
            return View(attributetype);
        }

        //
        // POST: /AttributeType/Edit/5

        [HttpPost]
        public ActionResult Edit(AttributeType attributetype)
        {
            if (ModelState.IsValid)
            {
                db.Entry(attributetype).State = EntityState.Modified;
                int userid = int.Parse(Session.Contents["UserID"].ToString());
                attributetype.ModifiedBy = userid;
                attributetype.ModifiedDate = DateTime.Now;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(attributetype);
        }

        //
        // GET: /AttributeType/Delete/5

        public ActionResult Delete(int id = 0)
        {
            AttributeType attributetype = db.AttributeTypes.Find(id);
            if (attributetype == null)
            {
                return HttpNotFound();
            }
            return View(attributetype);
        }

        //
        // POST: /AttributeType/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            AttributeType attributetype = db.AttributeTypes.Find(id);
            db.AttributeTypes.Remove(attributetype);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

IMS_V1/Controllers/Attribute_LookupController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IMS_V1.Controllers
{
    public class Attribute_LookupController : Controller
    {
        private IMS_V1Entities db = new IMS_V1Entities();

        //
        // GET: /Attribute_Lookup/

        public ActionResult Index(int id)
        {
            //var itemattribute = db.ItemAttributes.Include(i => i.Attribute_Lookup.AttributeType).Include(i => i.Item).Where(i => i.Item_Id == id);
            //var attributelookup = db.Attribute_Lookup.Where(al => al.AttributeType_Id == id && al.Active == true).OrderBy(al => al.WebsiteAttributeValue);
            var attributelookup = db.Attribute_Lookup.Where(al => al.AttributeType_Id == id).OrderByDescending(al => al.Active).ThenBy(al => al.WebsiteAttributeValue);
            ViewBag.AttributeType = db.AttributeTypes.Where(at => at.AttributeType_Id == id).Select(at => at.AttributeType1).Single();
            ViewBag.AttributeType_Id = id;


           //var attribute_lookup = db.Attribute_Lookup.Include(a => a.AttributeType);
            return View(attributelookup.ToList());
        }

        //
        // GET: /Attribute_Lookup/Details/5

        public ActionResult Details(int id = 0)
        {
            Attribute_Lookup attribute_lookup = db.Attribute_Lookup.Find(id);
            if (attribute_lookup == null)
            {
                return HttpNotFound();
            }
            return View(attribute_lookup);
        }

        //
        // GET: /Attribute_Lookup/Create

        public ActionResult Create(int id)
        {
            ViewBag.AttributeType_Id = id;

            ViewBag.AttributeType = db.AttributeTypes.Where(at => at.AttributeType_Id == id ).Select(at => at.AttributeType1).Single();
            return View();
        }

        //
        // POST: /Attribute_Lookup/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Exclude = "AttributeLookup_Id")]Attribute_Lookup attribute_lookup)
        {
            if (ModelState.IsValid)
            {
                int userid = int.Parse(Session.Contents["UserID"].ToString());
                db.Attribute_Lookup.Add(attribute_lookup);
                attribute_lookup.AttributeType_Id = attribute_lookup.AttributeType_Id;
                attribute_lookup.ModifiedBy = userid;
                attribute_lookup.ModifiedDate = DateTime.Now;
                db.SaveChanges();
                int attributetype_id = attribute_lookup.AttributeType_Id;//db.ItemAttributes.Where(ia => ia.ItemAttribute_Id == id).Select(ia => ia.Item_Id).Single();
                var attributelookup = db.Attribute_Lookup.Where(al => al.AttributeType_Id == attributetype_id && al.Active == true).OrderBy(al => al.APlusAttributeValue);
                ViewBag.AttributeType = db.AttributeTypes.Where(at => at.AttributeType_Id == attributetype_id).Select(at => at.AttributeType1).Single();
                ViewBag.AttributeType_Id = attributetype_id;

                return RedirectToAction("Index", new { id = attribute_lookup.AttributeType_Id });
            }

            ViewBag.AttributeType_Id = new SelectList(db.AttributeTypes, "AttributeType_Id", "AttributeType1", attribute_lookup.AttributeType_Id);
            return View(attribute_lookup);
        }

        //
        // GET: /Attribute_Lookup/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Attribute_Lookup attribute_lookup = db.Attribute_Lookup.Find(id);
            if (attribute_lookup == null)
            {
                return HttpNotFound();
            }
            ViewBag.AttributeType_Id = new SelectList(db.AttributeTypes, "AttributeType_Id", "AttributeType1", attribute_lookup.AttributeType_Id);
            int attributetypeid = attribute_lookup.AttributeType_Id;
            ViewBag.AttributeType = db.AttributeTypes.Where(at => at.AttributeType_Id == attributetypeid).Select(at => at.AttributeType1).Single();
            return View(attribute_lookup);
        }

        //
        // POST: /Attribute_Lookup/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Attribute_Lookup attribute_lookup)
        {
            if (ModelState.IsValid)
            {
                int userid = int.Parse(Session.Contents["UserID"].ToString());
                db.Attribute_Lookup.Add(attribute_lookup);
                attribute_lookup.ModifiedBy = userid;
                attribute_lookup.ModifiedDate = DateTime.Now;
                db.Entry(attribute_lookup).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { id = attribute_lookup.AttributeType_Id });
            }
            ViewBag.AttributeType_Id = new SelectList(db.AttributeTypes, "AttributeType_Id", "AttributeType1", attribute_lookup.AttributeType_Id);
            return View(attribute_lookup);
        }

        //
        // GET: /Attribute_Lookup/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Attribute_Lookup attribute_lookup = db.Attribute_Lookup.Find(id);
            ViewBag.AttributeType_Id = new SelectList(db.AttributeTypes, "AttributeType_Id", "AttributeType1", attribute_lookup.AttributeType_Id);
            int attributetypeid = attribute_lookup.AttributeType_Id;
            ViewBag.AttributeType = db.AttributeTypes.Where(at => at.AttributeType_Id == attributetypeid).Select(at => at.AttributeType1).Single();
            if (attribute_lookup == null)
            {
                return HttpNotFound();
            }
            return View(attribute_lookup);
        }

        //
        // POST: /Attribute_Lookup/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Attribute_Lookup attribute_lookup = db.Attribute_Lookup.Find(id);
            db.Attribute_Lookup.Remove(attribute_lookup);
            db.SaveChanges();
            return RedirectToAction("Index", new { id = attribute_lookup.AttributeType_Id });
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

IMS_V1/Views/Attribute_Lookup/Create.cshtml
@model IMS_V1.Attribute_Lookup

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
        <br />
    <br />
    <table>
        <tr>
            <td colspan="2" style="text-align:center;">
                <h2>New Attribute Lookup</h2>
            </td>
        </tr>
        <tr>
            <td colspan="2" style="text-align:left;">
                Attribute Type: @ViewBag.AttributeType
            </td>
        </tr>
        <tr>
            <td>
                <div class="editor-label">
                    @Html.HiddenFor(model => model.AttributeLookup_Id)
                    @Html.HiddenFor(model => model.AttributeType_Id, new {@Value = ViewBag.AttributeType_Id } )
                    @Html.LabelFor(model => model.WebsiteAttributeValue):
                </div>
            </td>
            <td>
                <div class="editor-field">
                    @Html.EditorFor(model => model.WebsiteAttributeValue)
                    @Html.ValidationMessageFor(model => model.WebsiteAttributeValue)
                </div>  
            </td>
        </tr>
        <tr>
            <td>
                <div class="editor-label">
                    @Html.LabelFor(model => model.APlusAttributeValue)
                </div>
            </td>
            <td>
                <div class="editor-field">
                    @Html.EditorFor(model => model.APlusAttributeValue)
                    @Html.ValidationMessageFor(model => model.APlusAttributeValue)
                </div>  
            </td>
        </tr>
        <tr>
            <td>
                <div class="editor-label">
                    @Html.LabelFor(model => model.DefaultActualValue)
                </div>
            </td>
            <td>
                <div class="editor-field">
                    @Html.EditorFor(model => model.DefaultActualValue)
                    @Html.ValidationMessageFor(model => model.DefaultActualValue)
                </div>  
            </td>
        </tr>
        <tr>
            <td>
                <div class="editor-label">
                    @Html.LabelFor(model => model.Active)
                </div>
            </td>
            <td>
                <div class="editor-field" style="text-align:left;">
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active)
                </div>  
            </td>
        </tr>
        <tr>
            <td colspan="2" style="text-align:center;">
                <input type="submit" value="Save" />
            </td>
        </tr>
    </table>
}
<div>
    @Html.ActionLink("Back to List", "Index", new{ id = ViewBag.AttributeType_Id })
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IMS_V1/Views/Attribute_Lookup/Delete.cshtml
@model IMS_V1.Attribute_Lookup

@{
    ViewBag.Title = "Delete";
}
    <br />
    <br />
    <table style="text-align:center;">
        <tr>
            <td colspan="4" style="text-align:center;">
                <h2>Delete Attribute Lookup</h2>
            </td>
        </tr>
        <tr>
            <th style="text-align:center;">
                Attribute Type
            </th>
            <th>
                WebSite Attribute Value
            </th>
            <th>
                APlus Attribute Value
            </th>
            <th>
                Default Attribute Value
            </th>
        </tr>
       <tr>
               
            <td style="text-align:center;">
                @Html.DisplayFor(model => model.AttributeType.AttributeType1)
                @Html.HiddenFor(model => model.AttributeLookup_Id)
            </td>
            <td style="text-align:left;">
                @Html.DisplayFor(model => model.WebsiteAttributeValue)
            </td>
            <td style="text-align:left;">
                @Html.DisplayFor(model => model.APlusAttributeValue)
            </td>
            <td style="text-align:left;">
                @Html.DisplayFor(model => model.DefaultActualValue)
            </td>
        </tr>
         <tr>
            <td style="text-align:center;" colspan="4">
                <h3>Are you sure you want to delete this?</h3>
            </td>
        <tr>
            <td colspan="4" style="text-align:center;">
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> 
    </p>
}
            </td>
        </tr>
    </table>

<div>
    @Html.ActionLink("Back to List", "Index", new{ id = Model.AttributeType_Id },null)
</div>

IMS_V1/Views/Attribute_Lookup/Details.cshtml
@model IMS_V1.Attribute_Lookup

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Attribute_Lookup</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.AttributeLookup_Id)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AttributeLookup_Id)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.AttributeType.AttributeType1)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AttributeType.AttributeType1)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.WebsiteAttributeValue)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.WebsiteAttributeValue)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.APlusAttributeValue)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.APlusAttributeValue)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DefaultActualValue)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DefaultActualValue)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ModifiedBy)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ModifiedBy)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ModifiedDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ModifiedDate)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id=Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

IMS_V1/Views/Attribute_Lookup/Edit.cshtml
@model IMS_V1.Attribute_Lookup

@{
    ViewBag.Title = "Edit";
}



@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
       <br />
    <br />
    <table>
        <tr>
            <td colspan="2" style="text-align:center;">
                <h2>Edit Attribute Lookup</h2>
            </td>
        </tr>
        <tr>
            <td colspan="2" style="text-align:left;">
                Attribute Type: @ViewBag.AttributeType
            </td>
        </tr>
        <tr>
            <td>
                <div class="editor-label">
                    @Html.HiddenFor(model => model.AttributeLookup_Id)
                    @Html.HiddenFor(model => model.AttributeType_Id)
                    @Html.LabelFor(model => model.WebsiteAttributeValue):
                </div>
            </td>
            <td>
                <div class="editor-field">
                    @Html.EditorFor(model => model.WebsiteAttributeValue)
                    @Html.ValidationMessageFor(model => model.WebsiteAttributeValue)
                </div>  
            </td>
        </tr>
        <tr>
            <td>
                <div class="editor-label">
                    @Html.LabelFor(model => model.APlusAttributeValue)
                </div>
            </td>
            <td>
                <div class="editor-field">
                    @Html.EditorFor(model => model.APlusAttributeValue)
                    @Html.ValidationMessageFor(model => model.APlusAttributeValue)
                </div>  
            </td>
        </tr>
        <tr>
            <td>
                <div class="editor-label">
                    @Html.LabelFor(model => model.DefaultActualValue)
                </div>
            </td>
            <td>
                <div class="editor-field">
                    @Html.EditorFor(model => model.DefaultActualValue)
                    @Html.ValidationMessageFor(model => model.DefaultActualValue)
                </div>  
            </td>
        </tr>
        <tr>
            <td>
                <div class="editor-label">
                    @Html.LabelFor(model => model.Active)
                </div>
            </td>
            <td>
                <div class="editor-field" style="text-align:left;">
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active)
                </div>  
            </td>
        </tr>
        <tr>
            <td colspan="2" style="text-align:center;">
                <input type="submit" value="Save" />
            </td>
        </tr>
    </table>
}

<div>
    @Html.ActionLink("Back to List", "Index", new{ id = Model.AttributeType_Id },null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IMS_V1/Views/Attribute_Lookup/Index.cshtml
@model IEnumerable<IMS_V1.Attribute_Lookup>

@{
    ViewBag.Title = "Attribute Values";
}


    <br />
    <br />
<table>
    <tr>
        <td colspan="3" style="text-align:center;">
            <h2>Attribute Values</h2>
        </td>
    </tr>
    <tr>
        <td colspan="3" style="text-align:left;">
            @Html.ActionLink("Create New", "Create", new { id = ViewBag.AttributeType_Id })
        </td>
    </tr>
    <tr>
        <td colspan="4" style="text-align:left;">
            Attribute Type: @ViewBag.AttributeType
        </td>
    </tr>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.WebsiteAttributeValue)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.APlusAttributeValue)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DefaultActualValue)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Active)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.WebsiteAttributeValue)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.APlusAttributeValue)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DefaultActualValue)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Active)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.AttributeLookup_Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.AttributeLookup_Id })
        </td>
    </tr>
}
        <tr>
        <td colspan="100" style="text-align:center">
             @Html.ActionLink("Back to List", "Index","AttributeType")
        </td>
    </tr>
</table>